export type ExtrasInstructions =
    | "Semicolon"
    | "Equals"
    | "Operator"
    | "Parentheses"
    | "ParenthesesEnd"
    | "Proxy"
    | "Block"
    | "BlockEnd"
    | "BlockStart"
    | "Array"
    | "ArrayEnd"
    | "Literal"
    | "Type"
    | "Return"
    | "ReturnIdentifier"
    | "Not";
